apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y9tqzpv3j-nodejs
  janus-idp.io/tekton: y9tqzpv3j-nodejs
  backstage.io/kubernetes-id: y9tqzpv3j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y9tqzpv3j-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
